### ISSUE TITLE
Private file sharing scenario

### ISSUE THREAD

**Issue by pmsoltani** [Quoorex/docker-bittorrent-tracker#4]
Hi

Thanks for making this repo. I have a question that I couldn't find a straight answer for so far, maybe you can help:

I'd like to share some of my files (on my MacBook), privately and using bit-torrent. I have [Transmission](https://transmissionbt.com) installed on my mac. When creating a new torrent file, it asks for trackers and I believe I should not use the public trackers out there, so I wanted to create my own.

![image](https://user-images.githubusercontent.com/25427031/102135604-77f78680-3e6d-11eb-887b-3e0d1b2f04c2.png)

Can you please walk me through the steps?

Suppose I have an AWS EC2 instance and have already pulled your image on it:
`docker run --rm -i -t quoorex/bittorrent-tracker:latest`

- What would be my tracker URL? (I have both my instance's public IP and its [Elastic IP](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html) at hand).
- Should I specify any hashes in the whitelist? If so why and how?
- Are there any other steps before I can share my `.torrent` files with my friends?

Appreciate your help 🙏

**Comment by Quoorex** [comment]
For your use case it would probably be simpler to just use the [embedded tracker of the torrent client qBittorrent](https://github.com/qbittorrent/qBittorrent/wiki/How-to-use-qBittorrent-as-a-tracker). That way you don't have to run a tracker on an AWS server.

**Comment by pmsoltani** [comment]
@Quoorex thanks for the reply. I've studied the link you provided. In the past, I did something similar using µTorrent on Windows. The solution, however, relies on port forwarding, and since portable computers are going to be connected to different networks, one may end up setting it up again and again. I should also point out that I did try to setup port forwarding on my router and for some reason, it failed when I tested it on [this tool](https://www.yougetsignal.com/tools/open-ports/) (mentioned in qBittorrent's guide).

So I believe setting up a tracker server on an EC2 instance would be a good idea. If it can be achieved using your docker image, I'd appreciate it if you could point out the steps.

**Comment by Quoorex** [comment]
You could use a public tracker. I'm not totally sure how safe that is, but as long as you flag the torrent as private and  encrypt your data beforehand you should be fine.
Alternatively you can also use no tracker at all. (This works through something called [DHT](https://stackoverflow.com/questions/1332107/how-does-dht-in-torrents-work))
Please note that you will probably have to port forward in order to transfer files using a torrent. If you don't, your transfer speed will be really slow.
Otherwise you can of course use this docker image. This project's readme should show you how to do it.
After you got the docker container running you can point your torrent client to 
`http://<public_ip>:<port>/announce`
or
`udp://<public_ip>:<port>/announce`
By default the tracker runs on port `8000`, but using docker you can map it to any port you want.

**Comment by pmsoltani** [comment]
I started my server using the image:

![image](https://user-images.githubusercontent.com/25427031/102487362-aea4eb00-407f-11eb-8822-d288aa87fb25.png)

Then I created 2 torrent files, one private and the other not private. I tested them using [zbigz](https://zbigz.com). After more than 12 hours, it could not download them:

![image](https://user-images.githubusercontent.com/25427031/102487639-283cd900-4080-11eb-9bbd-8d6f3cbfa1a1.png)

Did I miss something?

**Comment by Quoorex** [comment]
There is probably something wrong with the software itself. Unfortunately I don't really have the time to  look into that right now, so I'd advise you to look into the alternatives I've mentioned. You can also look for another tracker software.

**Comment by pmsoltani** [comment]
Alright. Thanks for the help.
